<?xml version="1.0" encoding="UTF-8"?><testsuite failures="2" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="2" time="16.039238">
<testcase classname="Login Action" name="Successful Login with Valid Credentials" time="8.527913">
<failure message="java.lang.AssertionError: expected [testuser_1] but found [Test@153]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:93)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:512)&#13;&#10;&#9;at org.testng.Assert.assertEqualsImpl(Assert.java:134)&#13;&#10;&#9;at org.testng.Assert.assertEquals(Assert.java:115)&#13;&#10;&#9;at org.testng.Assert.assertEquals(Assert.java:189)&#13;&#10;&#9;at org.testng.Assert.assertEquals(Assert.java:199)&#13;&#10;&#9;at stepdefinition.Parameters.user_enters_and(Parameters.java:41)&#13;&#10;&#9;at ✽.And User enters &quot;testuser_1&quot; and &quot;Test@153&quot;(parameters.feature:7)&#13;&#10;"><![CDATA[Given User is on Home Page..................................................passed
When User Navigate to LogIn Page............................................passed
And User enters "testuser_1" and "Test@153".................................failed
Then Message displayed Login Successfully...................................skipped

StackTrace:
java.lang.AssertionError: expected [testuser_1] but found [Test@153]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at stepdefinition.Parameters.user_enters_and(Parameters.java:41)
	at ✽.And User enters "testuser_1" and "Test@153"(parameters.feature:7)
]]></failure>
</testcase>
<testcase classname="Login Action" name="Successful Login with Valid Credentials 2" time="7.511325">
<failure message="java.lang.AssertionError: expected [testuser_2] but found [Test@153]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:93)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:512)&#13;&#10;&#9;at org.testng.Assert.assertEqualsImpl(Assert.java:134)&#13;&#10;&#9;at org.testng.Assert.assertEquals(Assert.java:115)&#13;&#10;&#9;at org.testng.Assert.assertEquals(Assert.java:189)&#13;&#10;&#9;at org.testng.Assert.assertEquals(Assert.java:199)&#13;&#10;&#9;at stepdefinition.Parameters.user_enters_and(Parameters.java:41)&#13;&#10;&#9;at ✽.And User enters &quot;testuser_2&quot; and &quot;Test@153&quot;(parameters.feature:7)&#13;&#10;"><![CDATA[Given User is on Home Page..................................................passed
When User Navigate to LogIn Page............................................passed
And User enters "testuser_2" and "Test@153".................................failed
Then Message displayed Login Successfully...................................skipped

StackTrace:
java.lang.AssertionError: expected [testuser_2] but found [Test@153]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at stepdefinition.Parameters.user_enters_and(Parameters.java:41)
	at ✽.And User enters "testuser_2" and "Test@153"(parameters.feature:7)
]]></failure>
</testcase>
</testsuite>
